package Utils;

public enum ErrorsEnum {

    ERROR_DATABASE,

    WRONG_PASSWORD,
    CLIENT_NOT_FOUND,

    LOGIN_SUCCESSFUL,
    LOGIN_WRONG_CREDENTIALS,
    LOGOUT_SUCCESSFUL,

    CLIENT_ADDED_SUCCESSFULLY,
    CLIENT_NOT_ADDED,
    CLIENT_REMOVED_SUCCESSFULLY,
    CLIENT_NOT_REMOVED,
    CLIENT_UPDATED_SUCCESSFULLY,
    CLIENT_NOT_UPDATED,
    CLIENT_ALREADY_EXISTS,

    TICKET_NOT_FOUND,
    TICKET_CREATED_SUCCESSFULLY,
    TICKET_UPDATED_SUCCESSFULLY,
    TICKET_BOUGHT_SUCCESSFULLY,

    TRIPS_NOT_AVAILABLE,
    TRIP_NOT_FOUND,
    TRIP_CREATED_SUCCESSFULLY,
    TRIP_NO_TICKETS_AVAILABLE,
    TRIP_REMOVED_SUCCESSFULLY,
    TRIP_UPDATED_SUCCESSFULLY,

    WALLET_INVALID_BALANCE,
    WALLET_NO_MONEY_AVAILABLE,
    WALLET_REFUNDED_SUCCESSFULLY,
    WALLET_UPDATED_SUCCESSFULLY
}
